### PR TITLE
restart background service after upgrade

### PR DESCRIPTION
**Pull request by 532910**
#592

### CODE REVIEW

**Comment by Viish** [comment]
Your PR won't work, the code in the boot receiver check that the service isn't running before starting it.

**Comment by 532910** [comment]
The app update stops the service.

**Comment by Viish** [comment]
Is there a documentation for that somewhere ?

**Comment by 532910** [comment]
https://stackoverflow.com/questions/30280089/what-happens-to-background-service-when-the-app-is-updated-in-android

**Comment by 532910** [comment]
https://stackoverflow.com/questions/31571743/retain-a-background-service-after-android-app-update

https://stackoverflow.com/questions/30242007/how-do-android-app-upgrades-work-technically/31149441#31149441

Is it sufficient?
Anyway, you can check it easily: just enable backgroud service and install the same apk after it.

**Comment by Viish** [comment]
Ok I did a bit differently:
```
commit 26d61fef4e2d15aa6fbe15d70b7a4577c9e93055 (HEAD -> release/4.2, origin/release/4.2, feature/restart_service_after_update)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Mon Oct 28 09:30:40 2019 +0100

    Restart service if foreground service setting is on when app is updated
```

**Comment by 532910** [comment]
Thank you!
Several days ago I've discovered https://gitlab.linphone.org/ and registered here. Is it better to open issues/PRs there or it doesn't matter?

**Comment by Viish** [comment]
For issues it is the same, for PR it's better to open them there, I can merge them directly if needed. Github is just a mirror.

**Comment by 532910** [comment]
Works fine!

**Pull request closed without merging**
